
name: Create Release and Tag
on:
  pull_request:
    types: [closed]

jobs:
  create_release_and_tag:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.merged == true) && (github.event.pull_request.base.ref == 'release') && (github.event.pull_request.title == 'Update docs')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.pull_request.head.ref }}
        release_name: Release ${{ github.event.pull_request.head.ref }}
        body: ${{ github.event.pull_request.body }}
        draft: true

    - name: Create tag with version number
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a ${{ github.event.pull_request.head.ref }} -m "${{ github.event.pull_request.body }}"
        git push origin ${{ github.event.pull_request.head.ref }}

  notify_failure:
    needs: create_release_and_tag
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get last committer email
        id: last_committer
        run: echo "::set-output name=email::$(git log -1 --pretty=format:'%ae')"

      - name: Send failure email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: GitHub Actions
          subject: Failed GitHub Actions run
          to: ${{ steps.last_committer.outputs.email }}
          body: |
            The update_pages job in the workflow run has failed. Check the logs for details.

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Event: ${{ github.event_name }}
